#!/bin/sh
# prerm for send-to-influx.deb
set -e

if [ -d /run/systemd/system ] && { [ "$1" = "remove" ] || [ "$1" = "purge" ]; }; then
    systemctl stop send-to-influx || true
    systemctl disable send-to-influx || true
fi

exit 0
